### ISSUE TITLE
text objects

### ISSUE THREAD

**Issue by MarcWeber** [austintaylor/vim-commaobject#2]
I think you should be using text object like mappings such as da, (delete a ,).
See :h text-objects

**Comment by austintaylor** [comment]
I'm not sure what you mean. This is a set of text-object mappings for comma-delimited arguments.

I have mappings for <kbd>a ,</kbd> and <kbd>i ,</kbd> in _operator pending mode_, which is useful for <kbd>d a ,</kbd> like you suggest, and also in _visual mode_ so you can <kbd>v a ,</kbd> to get a visual selection. As far as I know, this is the standard way to implement text objects in Vim.

**Comment by MarcWeber** [comment]
Unbelievable, I got what onoremap is about. Sorry for the noise and thanks for the plugin.

**Comment by MarcWeber** [comment]
There are related plugins, and your's is not on www.vim.org - or did I miss it

http://www.vim.org/scripts/script.php?script_id=2979
http://www.vim.org/scripts/script.php?script_id=2699
